ruoyi:
  name: RuoYi
  version: 3.9.0
  copyrightYear: 2025
  profile: C:/ruoyi/uploadPath
  addressEnabled: false
  captchaType: math
server:
  port: 8081
  servlet:
    context-path: /
  tomcat:
    uri-encoding: UTF-8
    accept-count: 1000
    threads:
      max: 800
      min-spare: 100
logging:
  level:
    com.ruoyi: debug
    org.springframework: warn
user:
  password:
    maxRetryCount: 5
    lockTime: 10
spring:
  messages:
    basename: i18n/messages
  profiles:
    active: druid
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
  devtools:
    restart:
      enabled: true
  mail:
    host: smtp.126.com
    port: 465
    username: wdb_workspace@126.com
    password: QMaxbvfSf8vGcECY
    properties:
      mail:
        smtp:
          ssl:
            enable: true
          auth: true
          connectiontimeout: 10000
          timeout: 10000
          writetimeout: 10000
  redis:
    host: localhost
    port: 6379
    database: 0
    password: Vfdgh@123yuyjN
    timeout: 10s
    lettuce:
      pool:
        min-idle: 0
        max-idle: 8
        max-active: 8
        max-wait: -1ms
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    druid:
      master:
        url: jdbc:mysql://localhost:3306/aiwe-vue?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
        username: root
        password: mysql123
      slave:
        enabled: false
        url: 
        username: root
        password: mysql123
      initialSize: 5
      minIdle: 10
      maxActive: 20
      maxWait: 60000
      connectTimeout: 30000
      socketTimeout: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      maxEvictableIdleTimeMillis: 900000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      webStatFilter: 
        enabled: true
      statViewServlet:
        enabled: true
        allow:
          url-pattern: /druid/*
        login-username: ruoyi
        login-password: 123456
      filter:
        stat:
          enabled: true
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: true
        wall:
          config:
            multi-statement-allow: true
token:
  header: Authorization
  secret: ZDrsarefzgAixizrhfhgfzdgbz
  expireTime: 30
mybatis:
  typeAliasesPackage: com.ruoyi.**.domain
  mapperLocations: classpath*:mapper/**/*Mapper.xml
  configLocation: classpath:mybatis/mybatis-config.xml
pagehelper:
  helperDialect: mysql
  supportMethodsArguments: true
  params: count=countSql
swagger:
  enabled: true
  pathMapping: /dev-api
xss:
  enabled: true
  excludes: /system/notice
  urlPatterns: /system/*,/monitor/*,/tool/*,/device/* 